import type { Question } from '@/types';

/**
 * Seção 1: Dados Pessoais + Saúde Oral + Saúde Médica + Prontuário
 * ~40 perguntas
 */

export const section1Questions: Question[] = [
  // === DADOS PESSOAIS ===
  {
    id: 'nome',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'text',
    label: 'Qual é o seu nome completo?',
    required: true,
    placeholder: 'Digite seu nome completo',
    dbField: 'dados_pessoais.nome',
  },
  {
    id: 'cpf',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'cpf',
    label: 'Qual o seu CPF?',
    description: 'Usamos seu CPF para salvar seu progresso. Se precisar parar, pode continuar de onde parou.',
    required: true,
    placeholder: '000.000.000-00',
    dbField: 'dados_pessoais.cpf',
  },
  {
    id: 'data_nascimento',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'date',
    label: 'Qual sua data de nascimento?',
    required: true,
    dbField: 'dados_pessoais.data_nascimento',
  },
  {
    id: 'endereco',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'text',
    label: 'Qual o seu endereço?',
    required: true,
    placeholder: 'Rua, número, bairro, cidade',
    dbField: 'dados_pessoais.endereco',
  },
  {
    id: 'celular',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'phone',
    label: 'Qual seu número de celular?',
    required: true,
    placeholder: '(00) 00000-0000',
    dbField: 'dados_pessoais.celular',
  },
  {
    id: 'email',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'email',
    label: 'Qual o seu e-mail?',
    required: false,
    placeholder: 'seu@email.com',
    dbField: 'dados_pessoais.email',
  },
  {
    id: 'contato_emergencia',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'text',
    label: 'Em caso de emergência, quem devemos avisar?',
    required: true,
    placeholder: 'Nome e parentesco',
    dbField: 'dados_pessoais.contato_emergencia',
  },
  {
    id: 'como_chegou',
    section: 1,
    subsection: 'Dados Pessoais',
    type: 'select',
    label: 'Como chegou até nós?',
    required: true,
    options: [
      { value: 'indicacao', label: 'Indicação' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'google', label: 'Google' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'outro', label: 'Outro' },
    ],
    dbField: 'dados_pessoais.como_chegou',
  },

  // === SAÚDE ORAL ===
  {
    id: 'tempo_escovacao',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'text',
    label: 'Quanto tempo leva escovando os dentes?',
    required: true,
    placeholder: 'Ex: 2 minutos',
    dbField: 'saude_oral.tempo_escovacao',
  },
  {
    id: 'mudar_sorriso',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'textarea',
    label: 'O que gostaria de mudar no seu sorriso?',
    required: true,
    placeholder: 'Descreva ou escreva "não se aplica"',
    dbField: 'saude_oral.mudar_sorriso',
  },
  {
    id: 'expectativa_tratamento',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'textarea',
    label: 'Qual sua expectativa para o tratamento?',
    required: true,
    placeholder: 'O que espera alcançar?',
    dbField: 'saude_oral.expectativa_tratamento',
  },
  {
    id: 'sensibilidade_frio',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Seus dentes são sensíveis ao frio?',
    required: true,
    dbField: 'saude_oral.sensibilidade_frio',
  },
  {
    id: 'fio_dental',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Utiliza fio dental todos os dias?',
    required: true,
    dbField: 'saude_oral.fio_dental',
  },
  {
    id: 'dor_doce_gelado',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Sente algum tipo de dor ao doce ou gelado?',
    required: true,
    dbField: 'saude_oral.dor_doce_gelado',
  },
  {
    id: 'aperta_dentes_stress',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Aperta os dentes quando submetido ao stress?',
    required: true,
    dbField: 'saude_oral.aperta_dentes_stress',
  },
  {
    id: 'range_dentes_noite',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Range os dentes durante a noite?',
    required: true,
    dbField: 'saude_oral.range_dentes_noite',
  },
  {
    id: 'dor_cabeca_refeicoes',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Sente dor de cabeça após as refeições?',
    required: true,
    dbField: 'saude_oral.dor_cabeca_refeicoes',
  },
  {
    id: 'extracao_implante',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Já foi submetido à extração ou implante dentário?',
    required: true,
    dbField: 'saude_oral.extracao_implante',
  },
  {
    id: 'gosto_ruim_halito',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Sente gosto ruim ou hálito desagradável?',
    required: true,
    dbField: 'saude_oral.gosto_ruim_halito',
  },
  {
    id: 'bochecho_diario',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Utiliza algum bochecho diário?',
    required: true,
    dbField: 'saude_oral.bochecho_diario',
  },
  {
    id: 'tratamento_periodontal',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Já fez algum tratamento periodontal?',
    required: true,
    dbField: 'saude_oral.tratamento_periodontal',
  },
  {
    id: 'tratamento_ortodontico',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Já fez tratamento ortodôntico?',
    required: true,
    dbField: 'saude_oral.tratamento_ortodontico',
  },
  {
    id: 'feliz_estetica',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Está feliz com sua estética bucal?',
    required: true,
    dbField: 'saude_oral.feliz_estetica',
  },
  {
    id: 'experiencia_ruim',
    section: 1,
    subsection: 'Saúde Oral',
    type: 'yes_no',
    label: 'Teve alguma experiência ruim em seu último tratamento odontológico?',
    required: true,
    dbField: 'saude_oral.experiencia_ruim',
  },

  // === SAÚDE MÉDICA ===
  {
    id: 'medicamento_diario',
    section: 1,
    subsection: 'Saúde Médica',
    type: 'yes_no_conditional',
    label: 'Toma algum medicamento diário?',
    required: true,
    followUp: {
      id: 'medicamento_diario_qual',
      section: 1,
      type: 'text',
      label: 'Qual medicamento?',
      required: true,
      placeholder: 'Nome do medicamento',
      dbField: 'saude_medica.medicamento_diario_qual',
    },
    dbField: 'saude_medica.medicamento_diario',
  },
  {
    id: 'acorda_noite',
    section: 1,
    subsection: 'Saúde Médica',
    type: 'yes_no_conditional',
    label: 'Acorda muitas vezes durante a noite?',
    required: true,
    followUp: {
      id: 'acorda_noite_quantas',
      section: 1,
      type: 'text',
      label: 'Quantas vezes acorda durante a noite?',
      required: true,
      placeholder: 'Ex: 2 a 3 vezes',
      dbField: 'saude_medica.acorda_noite_quantas',
    },
    dbField: 'saude_medica.acorda_noite',
  },
  {
    id: 'banheiro_noite',
    section: 1,
    subsection: 'Saúde Médica',
    type: 'yes_no_conditional',
    label: 'Vai muitas vezes ao banheiro durante a noite?',
    required: true,
    followUp: {
      id: 'banheiro_noite_quantas',
      section: 1,
      type: 'text',
      label: 'Quantas vezes vai ao banheiro durante a noite?',
      required: true,
      placeholder: 'Ex: 2 a 3 vezes',
      dbField: 'saude_medica.banheiro_noite_quantas',
    },
    dbField: 'saude_medica.banheiro_noite',
  },
  {
    id: 'tratamento_medico',
    section: 1,
    subsection: 'Saúde Médica',
    type: 'yes_no',
    label: 'Está em algum tratamento médico?',
    required: true,
    dbField: 'saude_medica.tratamento_medico',
  },
  {
    id: 'historico_medico',
    section: 1,
    subsection: 'Saúde Médica',
    type: 'checkbox_group',
    label: 'Marque os itens que se aplicam ao seu histórico médico:',
    description: 'Selecione todos que correspondem ao seu caso',
    required: false,
    options: [
      { value: 'febre_reumatica', label: 'Febre reumática' },
      { value: 'doencas_articulares', label: 'Doenças articulares' },
      { value: 'problemas_coracao', label: 'Problemas no coração (sopro, prolapso...)' },
      { value: 'hipertensao', label: 'Hipertensão' },
      { value: 'diabetes', label: 'Diabetes' },
      { value: 'endocardite', label: 'Endocardite bacteriana' },
      { value: 'problemas_digestivo', label: 'Problemas no trato digestivo' },
      { value: 'dores_cabeca', label: 'Dores de cabeça frequentes' },
      { value: 'bronquite_asma', label: 'Bronquite, asma ou sinusite' },
      { value: 'pes_tornozelos', label: 'Pés ou tornozelos inchados' },
      { value: 'hepatite', label: 'Hepatite, icterícia' },
      { value: 'dst', label: 'Alguma DST' },
      { value: 'catapora', label: 'Catapora' },
      { value: 'caxumba', label: 'Caxumba' },
      { value: 'hospitalizado', label: 'Já foi hospitalizado' },
      { value: 'cirurgia', label: 'Já foi submetido a alguma cirurgia' },
    ],
    dbField: 'saude_medica.historico_medico',
  },

  // === PRONTUÁRIO ===
  {
    id: 'comentarios',
    section: 1,
    subsection: 'Prontuário',
    type: 'textarea',
    label: 'Comentários pessoais',
    description: 'Algo mais que gostaria de compartilhar sobre sua saúde?',
    required: false,
    placeholder: 'Escreva aqui ou deixe em branco',
    dbField: 'prontuario.comentarios',
  },
  {
    id: 'alergia_medicamento',
    section: 1,
    subsection: 'Prontuário',
    type: 'yes_no_conditional',
    label: 'Possui alergia a algum medicamento?',
    required: true,
    followUp: {
      id: 'alergia_qual',
      section: 1,
      type: 'text',
      label: 'Qual medicamento?',
      required: true,
      placeholder: 'Nome do medicamento',
      dbField: 'prontuario.alergia_qual',
    },
    dbField: 'prontuario.alergia_medicamento',
  },
  {
    id: 'gravida_amamentando',
    section: 1,
    subsection: 'Prontuário',
    type: 'yes_no',
    label: 'Está grávida ou amamentando?',
    required: true,
    dbField: 'prontuario.gravida_amamentando',
  },
  {
    id: 'reposicao_hormonal',
    section: 1,
    subsection: 'Prontuário',
    type: 'yes_no',
    label: 'Faz reposição hormonal?',
    required: true,
    dbField: 'prontuario.reposicao_hormonal',
  },
  {
    id: 'menopausa',
    section: 1,
    subsection: 'Prontuário',
    type: 'yes_no',
    label: 'Já passou pela menopausa?',
    required: true,
    dbField: 'prontuario.menopausa',
  },
  {
    id: 'anticoncepcional',
    section: 1,
    subsection: 'Prontuário',
    type: 'yes_no_conditional',
    label: 'Utiliza algum anticoncepcional?',
    required: true,
    followUp: {
      id: 'anticoncepcional_qual',
      section: 1,
      type: 'text',
      label: 'Qual anticoncepcional?',
      required: true,
      placeholder: 'Ex: Mirena, pílula...',
      dbField: 'prontuario.anticoncepcional_qual',
    },
    dbField: 'prontuario.anticoncepcional',
  },
];
