import type { Question } from '@/types';

/**
 * Seção 2: Neuroplasticidade
 * ~50 perguntas: queixa principal, hábitos, mapa de dor,
 * dores orofaciais, distúrbios do sono, transtornos crônicos, medidas físicas
 */

const frequencyOptions = [
  { value: 'nunca', label: 'Nunca', color: '#10B981' },
  { value: 'de_vez_em_quando', label: 'De vez em quando', color: '#F59E0B' },
  { value: 'com_muita_frequencia', label: 'Com muita frequência', color: '#EF4444' },
];

export const section2Questions: Question[] = [
  // === QUEIXA PRINCIPAL ===
  {
    id: 'queixa_principal',
    section: 2,
    subsection: 'Queixa Principal',
    type: 'textarea',
    label: 'Qual é sua queixa principal?',
    description: 'Descreva o que mais te incomoda',
    required: true,
    placeholder: 'Descreva aqui...',
    dbField: 'neuroplasticidade.queixa_principal',
  },
  {
    id: 'neuro_comentarios',
    section: 2,
    subsection: 'Queixa Principal',
    type: 'textarea',
    label: 'Comentários pessoais',
    required: false,
    placeholder: 'Algo mais que queira compartilhar?',
    dbField: 'neuroplasticidade.comentarios',
  },
  {
    id: 'data_inicio_problema',
    section: 2,
    subsection: 'Queixa Principal',
    type: 'text',
    label: 'Data provável do início do problema',
    required: false,
    placeholder: 'Ex: Há 2 anos, desde 2020...',
    dbField: 'neuroplasticidade.data_inicio',
  },
  {
    id: 'tratamentos_anteriores',
    section: 2,
    subsection: 'Queixa Principal',
    type: 'textarea',
    label: 'Tratamentos anteriores',
    required: false,
    placeholder: 'Tratamentos que já fez para este problema',
    dbField: 'neuroplasticidade.tratamentos_anteriores',
  },

  // === HÁBITOS ===
  {
    id: 'evacua_diariamente',
    section: 2,
    subsection: 'Hábitos',
    type: 'yes_no',
    label: 'Evacua todos os dias?',
    required: true,
    dbField: 'neuroplasticidade.evacua_diariamente',
  },
  {
    id: 'desconforto_abdominal',
    section: 2,
    subsection: 'Hábitos',
    type: 'yes_no',
    label: 'Você tem desconforto abdominal ou gases com frequência?',
    required: true,
    dbField: 'neuroplasticidade.desconforto_abdominal',
  },
  {
    id: 'horario_dormir',
    section: 2,
    subsection: 'Hábitos',
    type: 'text',
    label: 'Qual horário você costuma dormir?',
    required: false,
    placeholder: 'Ex: 23:00',
    dbField: 'neuroplasticidade.horario_dormir',
  },
  {
    id: 'horario_acordar',
    section: 2,
    subsection: 'Hábitos',
    type: 'text',
    label: 'Qual horário você costuma acordar?',
    required: false,
    placeholder: 'Ex: 07:00',
    dbField: 'neuroplasticidade.horario_acordar',
  },
  {
    id: 'atividade_fisica',
    section: 2,
    subsection: 'Hábitos',
    type: 'select',
    label: 'Você pratica atividade física?',
    required: true,
    options: [
      { value: 'nao_pratico', label: 'Não pratico' },
      { value: 'raramente', label: 'Raramente' },
      { value: 'frequentemente', label: 'Frequentemente' },
    ],
    dbField: 'neuroplasticidade.atividade_fisica',
  },
  {
    id: 'freq_atividade',
    section: 2,
    subsection: 'Hábitos',
    type: 'number',
    label: 'Quantos dias por semana você pratica?',
    required: false,
    min: 0,
    max: 7,
    placeholder: '0-7',
    conditionalOn: { questionId: 'atividade_fisica', value: 'frequentemente' },
    dbField: 'neuroplasticidade.freq_atividade',
  },
  {
    id: 'periodo_atividade',
    section: 2,
    subsection: 'Hábitos',
    type: 'select',
    label: 'Em que parte do dia pratica?',
    required: false,
    options: [
      { value: 'manha', label: 'Manhã' },
      { value: 'tarde', label: 'Tarde' },
      { value: 'noite', label: 'Noite' },
    ],
    conditionalOn: { questionId: 'atividade_fisica', value: 'frequentemente' },
    dbField: 'neuroplasticidade.periodo_atividade',
  },

  // === MAPA DE DOR ===
  {
    id: 'pain_map',
    section: 2,
    subsection: 'Mapa de Dor',
    type: 'pain_map',
    label: 'Escala numérica da dor: marque de 0 a 10',
    description: 'Toque em cada região para indicar a intensidade da dor',
    required: true,
    dbField: 'pain_map',
  },
  {
    id: 'freq_dor',
    section: 2,
    subsection: 'Mapa de Dor',
    type: 'select',
    label: 'Frequência média da dor',
    required: true,
    options: [
      { value: 0, label: 'Raramente' },
      { value: 1, label: 'Mensal' },
      { value: 2, label: 'Semanal' },
      { value: 3, label: 'Diariamente' },
    ],
    dbField: 'neuroplasticidade.freq_dor',
  },
  {
    id: 'tipo_dor',
    section: 2,
    subsection: 'Mapa de Dor',
    type: 'select',
    label: 'Tipo da dor',
    required: true,
    options: [
      { value: 'pulsatil', label: 'Pulsátil ou Latejante' },
      { value: 'continua', label: 'Contínua' },
      { value: 'choque', label: 'Choque' },
      { value: 'queimacao', label: 'Queimação' },
      { value: 'outras', label: 'Outras' },
    ],
    dbField: 'neuroplasticidade.tipo_dor',
  },
  {
    id: 'comentarios_dor',
    section: 2,
    subsection: 'Mapa de Dor',
    type: 'textarea',
    label: 'Comentários sobre suas dores',
    required: false,
    placeholder: 'Descreva quando e como sente as dores...',
    dbField: 'neuroplasticidade.comentarios_dor',
  },

  // === SEÇÃO 1: DORES OROFACIAIS ===
  {
    id: 'orofacial_1',
    section: 2,
    subsection: 'Dores Orofaciais',
    type: 'scale_0_2',
    label: 'Tem dificuldades e/ou dor para movimentar a boca ou mastigar alimentos duros?',
    required: true,
    options: frequencyOptions,
    dbField: 'orofacial.dificuldade_mastigar',
  },
  {
    id: 'orofacial_2',
    section: 2,
    subsection: 'Dores Orofaciais',
    type: 'scale_0_2',
    label: 'Tem ruídos na articulação (próximos ao ouvido) durante a abertura da boca ou a mastigação?',
    required: true,
    options: frequencyOptions,
    dbField: 'orofacial.ruidos_articulacao',
  },
  {
    id: 'orofacial_3',
    section: 2,
    subsection: 'Dores Orofaciais',
    type: 'scale_0_2',
    label: 'Tem histórico de dores nos dentes (Restaurações/tratamentos de canal)?',
    required: true,
    options: frequencyOptions,
    dbField: 'orofacial.dores_dentes',
  },
  {
    id: 'orofacial_4',
    section: 2,
    subsection: 'Dores Orofaciais',
    type: 'scale_0_2',
    label: 'Tem histórico de sinusite?',
    required: true,
    options: frequencyOptions,
    dbField: 'orofacial.sinusite',
  },
  {
    id: 'comentarios_orofacial',
    section: 2,
    subsection: 'Dores Orofaciais',
    type: 'textarea',
    label: 'Comentários pessoais sobre dores orofaciais',
    required: false,
    placeholder: 'Detalhes adicionais...',
    dbField: 'orofacial.comentarios',
  },

  // === SEÇÃO 2: DISTÚRBIO DO SONO ===
  {
    id: 'sono_1',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'scale_0_2',
    label: 'Acorda cansado, desconforto e/ou dor nos músculos da face ou cefaleias matinais?',
    required: true,
    options: frequencyOptions,
    dbField: 'sleep_disorders.cansaco_matinal',
  },
  {
    id: 'sono_2',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'scale_0_2',
    label: 'Tem algum destes problemas durante o sono: transtorno respiratório, sono inquieto, despertar frequente, crises de asfixia, movimentos periódicos das pernas, acorda à noite com sudorese ou boca seca?',
    required: true,
    options: frequencyOptions,
    dbField: 'sleep_disorders.problemas_sono',
  },
  {
    id: 'sono_3',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'scale_0_2',
    label: 'Usa medicamentos para dormir (Tranquilizantes, calmantes, etc.)?',
    required: true,
    options: frequencyOptions,
    dbField: 'sleep_disorders.medicamentos_dormir',
  },
  {
    id: 'sono_4',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'scale_0_2',
    label: 'Ronca?',
    required: true,
    options: frequencyOptions,
    dbField: 'sleep_disorders.ronca',
  },
  {
    id: 'sono_5',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'scale_0_2',
    label: 'Sente deterioração da memória, falta de concentração, fadiga física ou mental, ou sonolência durante o dia?',
    required: true,
    options: frequencyOptions,
    dbField: 'sleep_disorders.fadiga_diurna',
  },
  {
    id: 'sono_6',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'scale_0_2',
    label: 'Você sabe se tem o sono agitado, se range ou aperta os dentes?',
    required: true,
    options: frequencyOptions,
    dbField: 'sleep_disorders.sono_agitado',
  },
  {
    id: 'comentarios_sono',
    section: 2,
    subsection: 'Distúrbio do Sono',
    type: 'textarea',
    label: 'Comentários pessoais sobre seu sono',
    required: false,
    placeholder: 'Detalhes adicionais...',
    dbField: 'sleep_disorders.comentarios',
  },

  // === SEÇÃO 3: TRANSTORNOS CRÔNICOS ===
  {
    id: 'cronico_1',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_2',
    label: 'Dor crônica (Enxaqueca, dores na face, dores nas costas, dores viscerais, fibromialgia ou outras)?',
    required: true,
    options: frequencyOptions,
    dbField: 'chronic_disorders.dor_cronica',
  },
  {
    id: 'cronico_2',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_2',
    label: 'Tem história de transtornos neurais (Déficit de atenção, síndrome do pânico, anorexia, bulimia, dislexia, TOC, etc.)?',
    required: true,
    options: frequencyOptions,
    dbField: 'chronic_disorders.transtornos_neurais',
  },
  {
    id: 'cronico_3',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_2',
    label: 'Faz uso crônico de medicamentos para alívio das dores ou por outros motivos?',
    required: true,
    options: frequencyOptions,
    dbField: 'chronic_disorders.uso_medicamentos',
  },
  {
    id: 'cronico_4',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_2',
    label: 'Sente ou tem alterações emocionais (crises de choro), falta de autoconfiança, sensação de fracasso, perda de libido, perda do apetite ou compulsão por comida, não tem motivação para se divertir?',
    required: true,
    options: frequencyOptions,
    dbField: 'chronic_disorders.alteracoes_emocionais',
  },
  {
    id: 'cronico_5',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_2',
    label: 'Utiliza em sua alimentação o glúten e/ou a lactose (pão, leite, etc.)?',
    required: true,
    options: frequencyOptions,
    dbField: 'chronic_disorders.gluten_lactose',
  },
  {
    id: 'cronico_6',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_2',
    label: 'Tem o hábito de consumir café, bebida alcoólica, tabaco, drogas, chocolate?',
    required: true,
    options: frequencyOptions,
    dbField: 'chronic_disorders.estimulantes',
  },
  {
    id: 'grau_ansiedade',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'scale_0_10',
    label: 'Qual seu grau de tensão e/ou ansiedade?',
    description: 'De 0 (nenhuma) a 10 (extrema)',
    required: true,
    min: 0,
    max: 10,
    dbField: 'chronic_disorders.grau_ansiedade',
  },
  {
    id: 'comentarios_cronicos',
    section: 2,
    subsection: 'Transtornos Crônicos',
    type: 'textarea',
    label: 'Comentários pessoais',
    required: false,
    placeholder: 'Detalhes adicionais...',
    dbField: 'chronic_disorders.comentarios',
  },

  // === MEDIDAS FÍSICAS ===
  {
    id: 'medidas_fisicas',
    section: 2,
    subsection: 'Medidas Físicas',
    type: 'bmi_calculator',
    label: 'Suas medidas físicas',
    description: 'O IMC será calculado automaticamente',
    required: true,
    dbField: 'physical_measurements',
  },
  {
    id: 'pressao_arterial',
    section: 2,
    subsection: 'Medidas Físicas',
    type: 'text',
    label: 'Pressão Arterial',
    required: false,
    placeholder: 'Ex: 12/8',
    dbField: 'physical_measurements.pressao_arterial',
  },
];
